### ISSUE TITLE
Append file extension for save dialog

### ISSUE THREAD

**Issue by angelog** [mlabbe/nativefiledialog#16]
This is something that Windows does by default (unsure about other platforms), if you type "test" and have a filter "txt" selected, it should automatically append ".txt" when you press enter.

**Comment by mlabbe** [comment]
I am open to a pull request that implements this as a conditional compile, disabled by default.

**Comment by nah0y** [comment]
Hello,

Seems like you just need to call :
`fileSaveDialog->SetDefaultExtension(L"");`
before calling AddFiltersToDialog and it works :)
