### ISSUE TITLE
Compile dll/so

### ISSUE THREAD

**Issue by Ulydev** [mlabbe/nativefiledialog#26]
Hello,

For a game project, I need to turn this library into a dll/so file.

I did some research but none of my attempts worked.

Can you please put me in the right direction?
Thanks.

**Comment by mlabbe** [comment]
Hi,

Currently, NFD has no build support for building as a dynamic library, though adding it would not prompt a significant reworking of the code or build system.  What is your reasoning for not statically linking it?

**Comment by Ulydev** [comment]
Hi,

Thanks for the fast reply!
I'm using LuaJIT's FFI library, which loads .dll and .so files.
http://luajit.org/ext_ffi.html

**Comment by mlabbe** [comment]
I am not a big lua user.  It appears someone has already taken a crack at this without using FFI. https://luarocks.org/modules/alloyed/nfd

At least one user of NFD previously reported modifying NFD to load as a DLL for their needs.  It was never offered as a pull request.

I would be happy to take a look at a pull request that implements this against the devel branch. i wrote a little on submitting pull requests: https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md  If you go this route, note that the devel branch implements a fourth function which has not been merged to master yet: NFD_PickFolder().

Alternatively, I can add it to the library for you if you are in a position to hire a consulting programmer.  Contract programming is how I make my living.

**Comment by mlabbe** [comment]
Hello!  Perhaps you could tip your hand as to what your plans are, or what you've discovered about Lua interop.  This is a relatively high traffic project, so I want to keep the open issues DB clean.  Thanks :)

**Comment by Ulydev** [comment]
Hi,
I ended up using this fork:
https://github.com/Alloyed/nativefiledialog/tree/master/lua

It compiles to .dll / .so and I was able to load it into FFI.
Thanks!
