### ISSUE TITLE
Better document dependencies

### ISSUE THREAD

**Issue by mlabbe** [mlabbe/nativefiledialog#27]
Currently, building for Linux requires you link libraries.  These are undocumented which means you'll just have to compile, receive errors, install libraries and then try again.

**Comment by Alloyed** [comment]
afaict (and this comes from my [luarocks package][pkg], which you can use as an example if you want) that just means having gtk 3 installed.
On ubuntu the package you'd want is `libgtk-3-dev`.
The cflags/ldflags can be gotten from pkg-config, like so:
```
pkg-config --cflags gtk+-3.0
pkg-config --libs gtk+-3.0
```
[pkg]: https://github.com/Alloyed/nativefiledialog/blob/master/lua/Makefile.linux

**Comment by mlabbe** [comment]
Thanks. This is documented in devel.
