### ISSUE TITLE
GTK+3: Dialog does not disappear

### ISSUE THREAD

**Issue by paniq** [mlabbe/nativefiledialog#3]
When using NFD from SDL, I noticed that the dialog never disappears after clicking Cancel or OK. It freezes and control is returned to the application as expected, but still remains in the foreground of the application. I can then call the window to the background and continue work. On the next call, the window appears as expected, but predictably shows the same behavior.

I would expect that the dialog disappears and focus is returned to the previous window.

**Comment by mlabbe** [comment]
That's just not happening for me over here.  I have NFD_SaveDialog() successfully disappearing in a program that hands its window management and event loop over to SDL.  I am linking against SDL 2.0.1 and libGTK-3 as ships with Ubuntu 14.04 (and Linux Mint 17).

I need advice on how to reproduce this or a pared down program that demonstrates the problem.

**Comment by paniq** [comment]
I'm running this in Ubuntu 12.10 with latest SDL from https://hg.libsdl.org/SDL and GTK+ 3.6.0. 

Based on a hunch I just tried the obvious and called WaitForCleanup() right after gtk_widget_destroy(dialog), and that fixed the problem. You might want to do the same.

**Comment by wysiwyng** [comment]
I'm experiencing the exact same issue running arch linux with sdl 1.2.15 and GTK+ 3.14.7. Using the fix described above fixes the problem for me.

**Comment by mlabbe** [comment]
I'm going to integrate the change as described as soon as I have time to test it.  I use NFD with SDL and it hasn't happened, but I don't want this to waste any more developer time.

**Comment by mlabbe** [comment]
Okay, I can't repro this bug, but I am going to fix it.  Can you confirm the solution is:

    gtk_widget_destroy(dialog);

    WaitForCleanup();
    +WaitForCleanup();
    
    return result;
}

**Comment by wysiwyng** [comment]
Yes, that fixes the problem for me. The same happens with the open multiple dialog.

**Comment by mlabbe** [comment]
Since I can't repro this over here, if you could pull my fix and test it, I would appreciate that.

**Comment by wysiwyng** [comment]
Nope, the dialog stays after calling and becomes unresponsive after selecting a file and clicking open. This only happens to the open and open multiple dialog though, the save dialog works fine. I believe the order of the function calls makes the difference. Putting `waitForCleanup(2)` after `gtk_widget_destroy()` fixes the problem, resp. doesn't introduce it in the first place in the save dialog.

**Comment by mlabbe** [comment]
Okay, I now understand.  Our previous conversation was not granular enough about the issue.  Proper fix coming up.

**Comment by mlabbe** [comment]
Fixed to that specification. Would appreciate a test and confirm.

**Comment by wysiwyng** [comment]
Yup, that does it. All three dialogs disappear beautifully. Thanks!

**Comment by mlabbe** [comment]
Thanks for helping drain the native file dialog swamp!
