### ISSUE TITLE
Android ndk support?

### ISSUE THREAD

**Issue by Turbine1991** [mlabbe/nativefiledialog#36]
Hi, while I realise this might be a bit harder to implement than Windows, Linux, Mac - It'd be a next-level feature. (It would open the default file manager)

**Comment by mlabbe** [comment]
Hey,

I don't think there is a clear path to get NFD running on NDK without substantially complicating the project. It would be a different build system to maintain (ndk-build), program flow would change, and it would introduce a need to synchronize the UI thread with the native thread (which may or may not be the UI thread -- it is not with SDL).

The way modal dialogs are handled would change as well.  Finally, the program could go into the background, and state would be removed.  Upon resume, we would need to make sure all data structures are available.

Finally, supporting a wide range of devices (hardware, screens, OS versions) is a test gauntlet.  NFD is depended up on by a large number of projects and I want to uphold the standard that it Just Works and Compiles On The First Try.

All of these things are possible, but daunting.  And certainly not something I would attempt without funding in place.

**Comment by devshgraphicsprogramming** [comment]
Would you accept a PR for such functionality?
