### ISSUE TITLE
ShellItem not released on error in Windows implementation

### ISSUE THREAD

**Issue by demurgos** [mlabbe/nativefiledialog#41]
Hi,
The following `ShellItem` is not released if an error is returned while using it (the function jumps to the end):

https://github.com/mlabbe/nativefiledialog/blob/5cfe5002eb0fac1e49777a17dec70134147931e2/src/nfd_win.cpp#L403

Similarly, the file dialog itself is never released.

Compare it to [the official example](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776913(v=vs.85).aspx#usage).

**Comment by mlabbe** [comment]
I agree, this needs doing!  If you offer a PR, I would be happy to merge it.

https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md

**Comment by mlabbe** [comment]
Friendly bump. If you have any time, I'd appreciate it.

**Comment by demurgos** [comment]
Thanks for the reminder.
I have a busy period at the moment and I'm not sure I'll be able to do it in January. I'll send a PR once I have more time.

**Comment by paulsapps** [comment]
Could maybe switch to use the RAII objects - the ComPtr<T> would auto call release in any circumstance

**Comment by mlabbe** [comment]
I implemented a fix for all of the cases on the devel branch.
