### ISSUE TITLE
No drop-down for filter groups in cocoa MAC picker

### ISSUE THREAD

**Issue by fuzzyweapon** [mlabbe/nativefiledialog#45]
No extension filter drop-down appears at all in cocoa pickers.  This definitely should be possible given browsers are able to invoke native file pickers with drop downs.

I am not putting in a separate issue for the fact that there is no automatic 'all' wildcard option when selecting since it might be a side effect of the above. (note that simply passing `null` for extensions does allow you to pick any file type)

_Found with High Sierra: Version 10.13.4 (17E199) using [lwjgl java bindings](https://javadoc.lwjgl.org/org/lwjgl/util/nfd/NativeFileDialog.html)_

**Comment by mlabbe** [comment]
This is not a Cocoa feature that can be turned on.  It should be possible to add a custom drop-down widget to an existing dialog.  If someone wants to take this on, start by reading https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md.

**Comment by mlabbe** [comment]
Closing issue as won't fix there has been no pull request in 18 months.  Still open to a PR on the issue.
