### ISSUE TITLE
Cannot pick multiple extensions in a single filter in cocoa picker

### ISSUE THREAD

**Issue by fuzzyweapon** [mlabbe/nativefiledialog#46]
If extensions are "txt,jpg" for example, you will only be able to pick .txt files in cocoa file picker.

_Found with High Sierra: Version 10.13.4 (17E199) using [lwjgl java bindings](https://javadoc.lwjgl.org/org/lwjgl/util/nfd/NativeFileDialog.html)_

**Comment by mlabbe** [comment]
Cannot reproduce using supplied tests on `"png,jpg;pdf"`.  All three work.  Check your downstream binding implementation.
