### ISSUE TITLE
Open multiple file cocoa dialog resurfaces after using Cancel or Okay buttons.

### ISSUE THREAD

**Issue by fuzzyweapon** [mlabbe/nativefiledialog#47]
This is an odd bug that looks similar to an older GTK bug and /only/ appears on the multiple file opening dialog.

1. Invoke multiple file open dialog.
2. Select a valid file.
3. Click `Cancel` or `Okay` _(double-clicking a selection will not trigger this bug)_.

_A Path_
4. Select another application on the same desktop to remove focus.
5. Select dialog application to give focus.
6. Observe that the dialog appears again, only the user cannot clear it and the file finder pain with file listings does not render.  There is no interactivity, but it clears out when the user kills the enclosing application.

_B Path_
4. Switch to another virtual desktop.
5. Switch back to the dialog application's desktop.
6. Observe that the dialog reappears as if first invoked.

_Found with High Sierra: Version 10.13.4 (17E199) using [lwjgl java bindings](https://javadoc.lwjgl.org/org/lwjgl/util/nfd/NativeFileDialog.html)_

**Comment by mlabbe** [comment]
Fixed by the same change that fixed #30 in devel branch.  Please test and reopen if not.
