### ISSUE TITLE
Linux compilation x86 ERROR with the given GMAKE

### ISSUE THREAD

**Issue by PicosePablo** [mlabbe/nativefiledialog#49]
Building with the configuration= debug|release x86 in linux cause this error:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:232:53: error: size of array ‘_GStaticAssertCompileTimeAssertion_0’ is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:229:47: note: in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:232:44: note: in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:423:3: note: in expansion of macro ‘G_STATIC_ASSERT’
   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
   ^~~~~~~~~~~~~~~
gmake[1]: *** [nfd.make:186: ../obj/x86/Debug/nfd/nfd_gtk.o] Error 1
gmake: *** [Makefile:51: nfd] Error 2

**Comment by mlabbe** [comment]
You are attempting to build against glib headers that are not compatible with your architecture.

`make help` shows how to specify the supported architectures.  `make config=release_x64` is probably what you want.
