### ISSUE TITLE
Add CMake project

### ISSUE THREAD

**Issue by irov** [mlabbe/nativefiledialog#50]
can I create a pull request and add to this project CMakeLists.txt?

**Comment by mlabbe** [comment]
Given that there are Premake-generated projects for each platform and architecture that is supported, we do not need Cmake.  Some of the original reasoning is available in this blog post:

https://www.frogtoss.com/labs/premake-for-package-maintainers.html

Adding Cmake in addition to Premake would increase the maintenance overhead and I already do not have a lot of free time.  I am not likely at all to accept a Premake pull request as a result of all these reasons.

**Comment by minexew** [comment]
@irov I think a battle-tested CMakeLists.txt would be very much appreciated by the community even if not upstreamed into the main project :))

**Comment by mlabbe** [comment]
There is an unofficial cmake file in vcpkg you can work with.  https://github.com/microsoft/vcpkg/tree/master/ports/nativefiledialog
