### ISSUE TITLE
Windows CoUninitialize() should only be called if CoInitializeEx() succeeded

### ISSUE THREAD

**Issue by btzy** [mlabbe/nativefiledialog#53]
Lines 369-373 of nfd_win.cpp (using devel branch):

```
if ( !SUCCEEDED(result))
{
    NFDi_SetError("Could not initialize COM.");
    goto end;
}
```

In the existing implementation, the above code is executed when CoInitializeEx() fails. `end` is where CoUninitialize() is called. Calling CoUninitialize() if CoInitializeEx() fails is wrong, according to the [MSDN documentation](https://docs.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-coinitializeex):

> To close the COM library gracefully on a thread, each successful call to CoInitialize or CoInitializeEx, including any call that returns S_FALSE, must be balanced by a corresponding call to CoUninitialize.

So we shouldn't be calling CoUninitialize() if it CoInitializeEx() does not succeed.

**Comment by mlabbe** [comment]
Fixed in f055c30.
