### ISSUE TITLE
NFD_PickFolder on Windows returns NFD_OKAY if the result IShellItem cannot be obtained

### ISSUE THREAD

**Issue by btzy** [mlabbe/nativefiledialog#54]
At line 732 of nfd_win.cpp (NFD_PickFolder), NFD_OKAY is returned if getting the IShellItem result fails. This is in contrast to line 408 of the same file (NFD_OpenDialog), in which NFD_ERROR is returned if getting the IShellItem result fails.

I suspect that line 732 should return NFD_ERROR instead.

**Comment by mlabbe** [comment]
Fixed in 31fb845e0c1.
