### ISSUE TITLE
Memory leak in AllocPathSet on Windows (nfd_win.cpp)

### ISSUE THREAD

**Issue by btzy** [mlabbe/nativefiledialog#55]
Lines 269 and lines 304 allocates memory to get the display name of a file:

```
LPWSTR name;
shellItem->GetDisplayName(SIGDN_FILESYSPATH, &name);
```

However, the code unfortunately forgets to call `CoTaskMemFree` to free `name`.

This memory leak happens on the non-error code path of `AllocPathSet`, so all callers of `NFD_OpenDialogMultiple` will experience the memory leak.

**Comment by mlabbe** [comment]
Fixed in f38519b6f.
