### ISSUE TITLE
NFD_SaveDialog defaultPath parameter has no effects - nfd_gtk.c

### ISSUE THREAD

**Issue by Dawid90dd** [mlabbe/nativefiledialog#6]
I noticed small bug. NFD_SaveDialog function don't set default path in nfd_gtk.c source. I've modified my copy of the source code by adding "SetDefaultPath(dialog, defaultPath); function to NFD_SaveDialog code. 

line 26
http://pastebin.com/CyR7dB5m

**Comment by mlabbe** [comment]
Yup, it's missing and it should be there!  I pushed a fix.  Thanks for the heads up.
