### ISSUE TITLE
Mac: file filters ignored when after longer extension

### ISSUE THREAD

**Issue by szakeetm** [mlabbe/nativefiledialog#66]
I call an NFD_OpenDialog with file filters "txt,html,htm"
On Windows and Linux, this behaves as expected.
On MacOS Mojave, I can only select txt and html files, not htm (they are greyed out).
When I change the filters to "txt,htm,html" it works.
It seems that a file filter extension is ignored if it's defined after an other extension with a larger number of characters.

**Comment by mlabbe** [comment]
This looks like a bug!  If you can put together a fix for it, I will accept the PR.  Here are the guidelines:

https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md

Thanks!

**Comment by mlabbe** [comment]
Fixed f939b05568fd258c900b928f10626ca217c3d450

**Comment by szakeetm** [comment]
Well done!
