### ISSUE TITLE
Windows compilation failure

### ISSUE THREAD

**Issue by gdorion** [mlabbe/nativefiledialog#67]
Hello,
Maybe I am doing something wrong.
When I am trying to compile on windows, using MinGW in msys2, current error is given
using the ming32-make.exe program to invoke compilation :

```
==== Building nfd (release_x64) ====
nfd_common.c
/usr/bin/sh: cc: command not found
nfd.make:176: recipe for target '../obj/x64/Release/nfd/nfd_common.o' failed
mingw32-make[1]: *** [../obj/x64/Release/nfd/nfd_common.o] Error 127
Makefile:48: recipe for target 'nfd' failed
mingw32-make: *** [nfd] Error 2

```
Seems like make file invokes Clang Compiler ?
Tried compilation on Mac OS and worked great.

Thanks a bunch.

**Comment by mlabbe** [comment]
This is failing to compile because you don't have a compiler in your path.  

`/usr/bin/sh: cc: command not found`

Put a compiler in your path and try again.
