### ISSUE TITLE
Compilation fails on VS2017

### ISSUE THREAD

**Issue by UltraFuture7000** [mlabbe/nativefiledialog#69]
Compilation on Visual Studio 2017 fails due to the following errors:
> E0546 transfer of control bypasses initialization of: variable (result) declared at line 384

and
> C2362 initialization of 'result' is skipped by 'goto end' 

Changing lines 374-384 in nfd_win.cpp from:
   ` if ( !SUCCEEDED(coResult))`
  `  {`
       ` fileOpenDialog = NULL;`
       ` NFDi_SetError("Could not initialize COM.");`
     `   goto end;`
 `   }`
  `  // Create dialog`
   ` HRESULT result = ::CoCreateInstance(::CLSID_FileOpenDialog, NULL,`
                                    `    CLSCTX_ALL, ::IID_IFileOpenDialog,`
                                    `    reinterpret_cast<void**>(&fileOpenDialog) );`

to:

 `HRESULT result = NULL;`
` if ( !SUCCEEDED(coResult))`
   ` {`
      `  fileOpenDialog = NULL;`
      `  NFDi_SetError("Could not initialize COM.");`
        `goto end;`
   ` }`
    `// Create dialog`
    `result = ::CoCreateInstance(::CLSID_FileOpenDialog, NULL,`
                                        `CLSCTX_ALL, ::IID_IFileOpenDialog,`
                                       ` reinterpret_cast<void**>(&fileOpenDialog) );`

seems to fix the issue and the dialogs work without any issues.

**Comment by UltraFuture7000** [comment]
This issue is not due to the window size variables.

**Comment by paulsapps** [comment]
You could probably also switch to using that small CComPtr object I added too

**Comment by mlabbe** [comment]
This doesn't happen on fresh checkout on vs2017 on the latest code as of the time of your posting.  You must be doing something else you're not describing.

**Comment by UltraFuture7000** [comment]
Perhaps that would be the case. I don't use Windows anymore so I am unable to reproduce the issue on an updated version on VS.
