### ISSUE TITLE
Focus for Mac Window

### ISSUE THREAD

**Issue by markusmoenig** [mlabbe/nativefiledialog#7]
Hi,

first of all thanks for the great work on the Native File Requester. We use it on www.visualgraphics.tv for multi os file requesters for the Desktops.

We have one issue which may not be yours. Under Mac / Cocoa we never succeed in setting the focus back to the SDL2 OpenGL Window after a Dialog was open. Resulting that the user has to select the main window once before being able to continue work.

Did you see this behavior too ?

Thanks again,

Markus

**Comment by mlabbe** [comment]
Hi Markus,

Yes, this is happening.  I would appreciate any patch or code snippet demonstrating how to reset the focus.

**Comment by mlabbe** [comment]
For example, with SDL2, you should be able to call SDL_GetWindowWMInfo(), which returns an SDL_SysWMInfo union.  https://wiki.libsdl.org/SDL_SysWMinfo

From there, you can get the NSWindow, from which you can call makeKeyAndOrderFront on.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/index.html#//apple_ref/occ/instm/NSWindow/makeKeyAndOrderFront:

While I don't want to add an explicit SDL or windowing dependency, I would be happy to accept a code snippet into docs if this works for you.

**Comment by markusmoenig** [comment]
Strange thing is, I tried this and it never worked to set the Focus back via Cocoa API calls. I always had to click on the Window. This may be some kind of conflict of SDL2 powered OpenGL windows with Cocoa. 

Anyway, it has been some time since I tried to get it to work last time, will retry it in the next days and will let you know.

**Comment by velkyel** [comment]
same issue here.  My simple solution is:

    NSWindow *keyWindow = [[NSApplication sharedApplication] keyWindow];
    // ...before [NSOpenPanel openPanel]

and

    [keyWindow makeKeyAndOrderFront:nil];
   // ...before return nfdResult;

that's it

**Comment by mlabbe** [comment]
That sounds promising!  Markus, can you try this and report back?

**Comment by markusmoenig** [comment]
Yes, works fine, thanks velkyel.

My issue was that I used the NSWindow supplied by SDL_SysWMinfo which is definitely not working for some reason. Can only imagine it is a bug in SDL2.

Thanks everybody for the help on this.

**Comment by mlabbe** [comment]
Thanks, everyone! I am going to update the project as soon as I have time!

The issue will be closed then.

**Comment by mlabbe** [comment]
Okay! This fix has finally been merged into master!
