### ISSUE TITLE
Compiled Library

### ISSUE THREAD

**Issue by prog-r-amer** [mlabbe/nativefiledialog#71]
Hello, 

could you maybe provide me with the compiled library to llink against? 
I'm not managing setting it up with mingw on windows 10, neither with visual studio 2017.

I would be very grateful.

Nice greetings,
Tobias

**Comment by prog-r-amer** [comment]
Ok, I managed to compile the library with visual studio but I still didn't manage to compile a simple test file with mingw and the library.

**Comment by mlabbe** [comment]
I'd like to support compiled binaries but my time is very limited.

Please update to 081cce2903f25e5e9e2727cbdc1b38fb4eed342e in the devel branch and re-attempt compilation with mingw.

Note that this change adds mingw configuration instructions in build.md.
