### ISSUE TITLE
NFD_SaveDialog is missing a pre-set filename

### ISSUE THREAD

**Issue by mlaggner** [mlabbe/nativefiledialog#77]
**Compilation Environment**

Java - LWJGL (version 3.2.3)

**Describe the bug**

I am missing an option to pre-set the filename for the NFD_SaveDialog. I am able to pre-set the path, but not the filename itself.

**User Description**

I am about to introduce NFD for the tool tinyMediaManager as a replacement of the JavaFX file open dialog (since there is no other dependency to JavaFX)

**Comment by nekitu** [comment]
yes, this is highly needed, voted

**Comment by mlabbe** [comment]
3f3e7956915bbbc355e0a2f6daf0e6c2080be001 on devel branch enables pre-set filenames for all relevant dialogs.
