### ISSUE TITLE
NFD_PickFolder not showing with pre-set path

### ISSUE THREAD

**Issue by mlaggner** [mlabbe/nativefiledialog#78]
**Compilation Environment**

Java - LWJGL (version 3.2.3); especially Windows

**Describe the bug**

When trying to open the NFD_PickFolder (and probably all other dialogs) with a pre-set UNC path which is not available (switched off NAS or not connected and password protected), NFD times out after about 10 seconds without showing any dialog (error is getting returned).

Other implementations of file open dialogs like JFileChooser display the dialog with a default path (home folder) after the 10 second timeout.

I wish NFD could behave the same way since it is not obvious for the user why the dialog has not been opened.

**User Description**

I am about to introduce NFD for the tool tinyMediaManager as a replacement of the JavaFX file open dialog (since there is no other dependency to JavaFX)

**Comment by mlabbe** [comment]
#94 describes missing behaviours on a per-OS basis, so, closing this.
