### ISSUE TITLE
[OSX] File Extensions filters < 3 chars not working

### ISSUE THREAD

**Issue by bazzinotti** [mlabbe/nativefiledialog#8]
I originally wanted to add a file extension for 7-zip files (7z) but it would not work.. After some experimenting, I found that "e7" also did not work but "e7e" did work... I also could not get "7z " or " 7z" to work.. 

I could not find any NFD code that alluded to constraining the file extension to 3-chars, making me wonder if this is a different issue outside of NFD.. here are the relevant functions regarding the filter list:

NFD_OpenDialogMultiple
AddFilterListToDialog
BuildAllowedFileTypes

I am not skilled with OBJC so I'm not sure how to fix the problem.

**Comment by bazzinotti** [comment]
OBJC debug message showing that the third char is inherited from the previous 3-char-extension (works with other chars)
2015-07-20 02:40:06.023 std[19136:584142] (
    spc,
    rsn,
    rar,
    7zr
)

Also, if I manually craft a NSArray it will work, ie
NSArray *array = @[@"spc", @"7z", @"rar"];

**Comment by bazzinotti** [comment]
OK I figured out the "apparent" solution .. not sure if this produces side-FX .. 
nfd_cocoa.m : 25
// remove or comment ++p_typebuf;

**Comment by bazzinotti** [comment]
here's a link to a commit where I fixed the issue for my project: https://github.com/bazzinotti/SNES-Tracker/commit/e79571ace96d40cc7676d924e7194408ed00e4bc

**Comment by mlabbe** [comment]
Thanks for the link!  Can you supply a simple, buildable program that demonstrates the bug? It might be convenient for you to do this by modifying one of the programs in the test subdir of the repo.

**Comment by bazzinotti** [comment]
I'm sorry but there's no way I'm going to do this. I guess I don't have the time.

**Comment by mlabbe** [comment]
This isn't a tumblr for your complaints, it's an issue tracker.   Don't come back.
