### ISSUE TITLE
[OSX] Dialog ignores mouse and keyboard events, also it does not capture focus

### ISSUE THREAD

**Issue by PolyMeilex** [mlabbe/nativefiledialog#86]
**Compilation Environment**

 - OS: OSX 19.6.0
 - Compiler: Clang
 - Compiler Version: 11.0.3
 - Build directory used:  `build/gmake_macosx`
 - Have I attempted to reproduce the problem on the `devel` branch?: Yes

**Describe the bug**
Dialog ignores mouse and keyboard events, also it does not capture focus
GIF:
_Top one is `nfd` dialog, bottom one is `osascript` dialog for comparasion_
![GIF](https://i.imgur.com/orDuaYR.gif)

**Comment by mlabbe** [comment]
Can you select the "macOS" folder drop down at the top?  

This is probably due to the fact that you are not running your app in a sandbox, and so it does not have full disk access.

**Comment by PolyMeilex** [comment]
I found a fix already, it is because `NSApplicationActivationPolicy` is set to `Prohibited` by default. Changing it to `Accessory` fixes the issue.

```objc
app = [NSApplication sharedApplication];
initial_policy = [app activationPolicy];
if (initial_policy == NSApplicationActivationPolicyProhibited) {
   [app setActivationPolicy:NSApplicationActivationPolicyAccessory];
}
```

**Comment by mlabbe** [comment]
Wonderful!  I am integrating a fix based on your tip.  Thanks for your help.

**Comment by ValuedAnt** [comment]
I've had a similar problem: trying out the Open File Dialog, I cannot select files or folders—unless I drag them, and then they become selected. Can't readily select volumes either. GIF attached:

![Image](https://github.com/user-attachments/assets/b90d4bc7-32ce-4bd7-a45c-3dfd3570e045)

This happens both in what I've compiled and the test versions. 

macOS 12.7.6, compiling Release with both GCC and Clang, on VS Code.
