### ISSUE TITLE
Add NFD_SaveDialog set extension arguments

### ISSUE THREAD

**Issue by irov** [mlabbe/nativefiledialog#87]
example for _WIN32 

`fileSaveDialog->SetDefaultExtension( L"txt" );`

thanks!

**Comment by mlabbe** [comment]
This is implemented in c0e491055bba7b6e0326e2d94566b65e6aebc014 on the devel branch.  No additional apis are needed -- the first extension in the filter list becomes the default extension on win32.  Please sync up devel branch and let me know asap.
