### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by grickel** [mlabbe/nativefiledialog#9]
Error	1	error LNK2019: unresolved external symbol _NFD_OpenDialog referenced in function _main	C:\Users\tsquare\User File's\Programing\C++ Form Prac\Nativefiledialog test\Nativefiledialog test\Source.obj

Sigh... I use Visual Studio. I go into proprieties -> C/C++ -> General -> Additional Include Directories ->  src and src/libs

<nfd.h> comes up yet I can't get past the error. What should I do?

**Comment by mlabbe** [comment]
This is happening because you are not linking the native file dialog library against your EXE.
You need to:
1. Specify the search path
2. Link against the native file dialog .lib file.

And before any of this, you have to generate the .lib file by building Native File Dialog with Scons.
