### ISSUE TITLE
[windows] does not autofill extension on File Save

### ISSUE THREAD

**Issue by bazz1tv** [mlabbe/nativefiledialog#90]
Hi,

First, thanks for creating NFD for us :)

Here's the gist of the problem: When I go to save a file through NFD on Windows (eg. win10), and I have a file extension filter "sts" when I type in the filename box "foo" it will save to a file "foo" rather than auto-completing to "foo.sts"

So many of my users are expecting it to save to "foo.sts" automatically. It seems NFD is not behaving as Windows users expect. It autofills on other operating systems IIRC such as Mac and Linux. I would really appreciate your support on this, as I enjoy using NFD <3

EDIT: I also experience this issue on Linux. IIRC Mac is the only platform that auto-completes the extension on save. I suppose I can just make the solution in software after NFD reports the filename by checking for the existence of the extension and appending it if necessary.

**Comment by mlabbe** [comment]
As of c0e491055bba7b6e0326e2d94566b65e6aebc014 this should work as expected.  Please sync up the devel branch and let me know asap.
