### ISSUE TITLE
File extensions menu

### ISSUE THREAD

**Issue by mottelet** [mlabbe/nativefiledialog#96]
Hello,

under macOS, how do you display the file extensions menu, like on the following screenshot:

![screenshot](https://user-images.githubusercontent.com/8794797/104756330-f5a7fe00-575b-11eb-8de2-4f73b8699f3e.png)

Thanks for your help.

S.

**Comment by mlabbe** [comment]
This is not supported.  I am still open to a PR that adds this. Relevant issue is https://github.com/mlabbe/nativefiledialog/issues/45

**Comment by mottelet** [comment]
Thanks !
